# Generated by Django 3.2 on 2021-05-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
